- hosts: all
  become: true
  tasks:
      - name: Pull latest Docker images
        docker_image:
            name: myuser/myproject
            source: pull

      - name: Copy docker-compose.yml
        copy:
            src: ./docker-compose.yml
            dest: /home/myuser/docker-compose.yml

      - name: Run Docker Compose
        command: docker-compose up -d
        args:
            chdir: /home/myuser
