version: '3.8'

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: mydb
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        ports:
            - '4444:5432'

    web:
        build: .
        command: gunicorn todo_api.wsgi:application --bind 0.0.0.0:2222
        volumes:
            - .:/app
        ports:
            - '1111:2222'
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        ports:
            - '3333:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - web
