name: CI/CD

on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8
            - name: Lint with flake8
              run: |
                  flake8 .

    test:
        runs-on: ubuntu-latest
        needs: lint
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_DB: test_db
                    POSTGRES_USER: test_user
                    POSTGRES_PASSWORD: test_password
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v2
            - name: Run tests
              run: |
                  python manage.py test

    build-and-push:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push
              run: |
                  docker build -t yourdockerhubusername/todo-api .
                  docker push yourdockerhubusername/todo-api
